spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1

task:
  grpc:
    host: localhost
    port: 9099

mock:
  server:
    url: http://localhost:8088
